[package]
name = "day8"
version = "0.1.0"
authors = ["Samarth Kishor <samarthkishor1@gmail.com>"]
edition = "2018"

[[bin]]
name = "day8"
path = "day8.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
